language: csharp
dotnet: 2.2


script:
    dotnet test Problems.Tests
    
matrix:
    include: 
       - os: linux
          dist: bionic
       - os: linux
          dist: xenial
       - os: macos
        
